sudo: required

language: generic

services:
- docker

install:
- docker build . -t arch -f dockerfiles/arch
- docker build . -t xenial -f dockerfiles/xenial

script:
- docker run -t arch make test
- docker run -t xenial make test
